source/borderrouter_tasklet.c
Removed the call to detect RF device type, this is not supported
on all platforms.
Requires https://github.com/ARMmbed/k64f-border-router/pull/37 to work.
=> Fix build with different RF phys.

configs/6lowpan_Atmel_RF.json, configs/6lowpan_Spirit1_RF.json, configs/Thread_Atmel_RF.json, configs/Thread_SLIP_Atmel_RF.json, drivers/TARGET_K64F/sal-nanostack-driver-k64f-eth.lib, drivers/TARGET_MCUXpresso_MCUS/sal-nanostack-driver-k64f-eth.lib, mbed_app.json, source/border_router_main.cpp
Add support to NXP K66F board.
Required driver change already pushed in: https://github.com/ARMmbed/sal-nanostack-driver-k64f-eth/commit/ee7e8a9a2122415d45b93eb8e1abdc933b1a9c97
=> K66F support

source/thread_bbr_ext.h, source/thread_br_conn_handler.c
Enable Thread mDNS responder when Ethernet and Thread networks
are active. Disable mDNS responder when either Thread or Ethernet interface
is down.
=> Enable Thread mDNS responder

source/border_router_main.cpp, source/borderrouter_tasklet.c, source/borderrouter_tasklet.h, source/borderrouter_thread_tasklet.c
This is to prevent API collision with internal Nanostack API
when compiling against sources of Nanostack.
=> Rename border_router_start() to border_router_tasklet_start()

source/borderrouter_thread_tasklet.c
Trace interface addresses in 20s intervals when tracing is enabled.
=> Trace interface address in 20s intervals

README.md
The link was referencing 5.4 docs.  Can be updated to reference the latest doc set.
=> Update link for adding target support to latest

source/thread_bbr_ext.h
Remove mDNS macros from header in order to use mDNS from Nanostack
=> Use mdns from mbed-os-5.5 release

source/borderrouter_tasklet.c
Support for long GP64 addresses instead of default GP16.
Note: This does not affect nodes, which needs also to choose addressing
mode.
=> ONME-3153: Support long addresses

README.md
Remove nanostack configuration from readme as nanostack configuration
is not meant to be configurable.
=> Remove nanostack configuration from README

configs/Thread_SLIP_Atmel_RF.json
Compile failed because the macro did not match the regular expression used to parse macros.
=> Fixed macro format to match regular expression

README.md, configs/6lowpan_Atmel_RF.json, configs/6lowpan_Spirit1_RF.json, configs/Thread_Atmel_RF.json, configs/Thread_SLIP_Atmel_RF.json, drivers/TARGET_NUCLEO_F429ZI/sal-nanostack-driver-stm32-eth.lib, mbed-os.lib, mbed_app.json, source/border_router_main.cpp, source/borderrouter_tasklet.c, source/borderrouter_thread_tasklet.c
Add new EMAC backhaul driver option that uses new mbed OS 5.9 EMAC and default network interface APIs. This should work for any Ethernet EMAC driver, and can work with appropriately-engineered Wifi drivers - see README.md for more details.
=> Add support for EMAC backhaul driver

configs/Thread_Atmel_RF.json, configs/Thread_SLIP_Atmel_RF.json
Thread BR requires 45k of heap to start properly.
Increase heap size from 40k to 64k.
Note: Thread will not compile with IAR.
=> Increase Nanostack heap size for Thread BR

README.md, configs/6lowpan_Atmel_RF.json, configs/6lowpan_Spirit1_RF.json, configs/Thread_Atmel_RF.json, configs/Thread_SLIP_Atmel_RF.json, drivers/TARGET_NUCLEO_F429ZI/sal-nanostack-driver-stm32-eth.lib, mbed-os.lib, mbed_app.json, source/border_router_main.cpp, source/borderrouter_tasklet.c, source/borderrouter_thread_tasklet.c
Revert EMAC changes pending 5.9.0 release.
This reverts commits 918feb6..935d777 (PRs #85 and #108).
=> Revert support for EMAC backhaul driver

source/mbedtls_thread_config.h
Enable MBEDTLS_CIPHER_MODE_CTR as it is required by SecureStore.cpp
=> Update mbedtls configuration

configs/Wisun_Stm_s2lp_RF.json
This fixes 2 issues with Wi-SUN config.
Escape characters were missing for parameters when using static border router.
mbed-mesh-api allocated static memory for heap causing too much memory used with IAR compilation
=> Configuration fixes for Wi-SUN

drivers/TARGET_MCUXpresso_MCUS/sal-nanostack-driver-k64f-eth.lib, source/border_router_main.cpp, source/mbedtls_thread_config.h
* sal-nanostack-driver-k64f-eth includes target specific header files that are not available for all targets.
Add target specific flags to k64f-eth-driver to allow builds for other targets.
* Fix IAR warning "incompatible redefinition of macro" 
* Add compiler stats to application
=> Allow compilation with non K64F/K66F boards

source/borderrouter_ws.c
mbed TLS expects null terminator to be calculated to PEM length.
=> Corrected Wi-SUN certificate length calculation

README.md, configs/6lowpan_Atmel_RF.json, configs/6lowpan_Spirit1_RF.json, configs/Thread_Atmel_RF.json, configs/Thread_SLIP_Atmel_RF.json, configs/Wisun_Stm_s2lp_RF_cell.json, source/border_router_main.cpp, source/borderrouter_ws.c
When configured to use cellular interface, creates PPP and onboard
network stack instances, and connects cellular interface.
When PPP interface goes up, reads interface identifier from PPP
service and creates link local address based on it.
=> Added support for Cellular PPP interface

source/border_router_main.cpp
Update the main() to be compatible with the declaration from
platform/mbed_toolchain.h that adds the MBED_USED attribute.
Without the attribute the main() symbol is not emitted with the
GCC toolchain using "-Wl,--wrap,main" and "-flto" flags.
This patch is required by https://github.com/ARMmbed/mbed-os/pull/11856.
=> Fix conflicting declarations of main() for GCC_ARM build with "-flto"

README.md, source/borderrouter_ws.c
Setting enables to set GTK0 on border router to fixed value for testing purposes.
=> Added support for network encryption key (GTK) set to border router

drivers/stm-spirit1-rf-driver.lib
Update new Spirit RF driver to mbed-os-5.15 branch to allow compilation with the latest Mbed OS master branch.
=> Update stm-spirit1-rf-driver to mbed-os-5.15 branch

drivers/stm-spirit1-rf-driver.lib
Update stm-spirit1-rf-driver to mbed-os-5.13 branch to allow compilation against Mbed OS master branch.
=> Update stm-spirit1-rf-driver to mbed-os-5.13 branch

drivers/stm-spirit1-rf-driver.lib
Update spirit RF driver to mbed-os-5.14 branch to allow compilation with new Mbed OS master.
=> Update stm-spirit1-rf-driver to mbed-os-5.14 branch

source/border_router_main.cpp
Add checks around MAC address read to avoid HardFault in case of
EthernetInterface creation fails.
=> Check interface before reading MAC address

Jenkinsfile, drivers/sal-stack-nanostack-slip.lib, mbed-os.lib
Update libraries in branch mbed-os-5.15.
- Use Slip driver that supports Mbed OS master (RawSerial replaced by UnbufferedSerial)
- Update Mbed OS version to mbed-os-5.15.2
- Remove IAR compilation from CI
=> Update libraries in mbed-os-5.15 branch

drivers/TARGET_MCUXpresso_MCUS/sal-nanostack-driver-k64f-eth.lib
Update sal-nanostack-driver-k64f-eth to allow compilation against Mbed OS master.
=> Update library sal-nanostack-driver-k64f-eth in mbed-os-5.15

configs/6lowpan_Atmel_RF.json, configs/Thread_Atmel_RF.json, configs/Wisun_Stm_s2lp_RF.json, custom_targets.json
Create configurations for border router testing.
Testable border routers can be compiled using targets:
-K64F_STATIC_BR
-DISCO_F769NI_STATIC_BR
=> Configuration for border router testing

README.md
- Change example board from NUCLEO_F429ZI to DISCO_F769ZI as F429ZI
has a PIN conflict when SPI is used.
- Add known issues, link NUCLEO_F429ZI SPI pin conflict document.
=> Update readme with SPI pin conflict
